### ISSUE TITLE
How to handle CUDA dependency

### ISSUE THREAD

**Issue by paskino** [TomographicImaging/CCPi-Regularisation-Toolkit#127]
So far the only package depending on CUDA is the regularisation. Currently we rely on the host to have CUDA installed. 
Jenkins doesn’t build for CUDA, though I seem to remember we used to do that. 

At any rate, the question is: how do we handle CUDA dependency? 

 - **Build** : CUDA must be present on the machine. Jenkins can have CUDA 8, 9 or 10. At the moment Jenkins does not have a GPU and cannot run tests. I seem to remember that we [addressed this](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/issues/79) and the tests are just skipped.

 - **Runtime**: CUDA must be present on the machine. If we build with CUDA 8, the package should work on any machine with CUDA >= 8.

All this is not documented in the package. 

There is another way to do this and it would be to depend on the package [cudatoolkit](https://anaconda.org/anaconda/cudatoolkit/) from conda. In this way we can just add cudatoolkit in the dependency in the meta.yaml and any machine to install the package will have the CUDA toolkit even if there’s no GPU on the machine.

I suppose this would be the default for the conda package?

Comments?

**Comment by paskino** [comment]
[Astra 1.8.3](https://github.com/astra-toolbox/astra-toolbox/blob/bfceef4da377c32cd59d1e51efb9aa1a21c7f4bd/python/conda/libastra/linux_build_config.yaml) (which isn't a dependency here but that we use) lists `cudatoolkit` in the conda package.

[This](https://github.com/astra-toolbox/astra-toolbox/blob/master/python/conda/libastra/linux_build_config.yaml) is astra current master

**Comment by dkazanc** [comment]
OK, so if we take cudatoolkit from conda as a dependency then can we use it to build the package? If we can then I'd guess it is the preferred way.  It also helps to cover for different versions of cudatoolkit?

**Comment by paskino** [comment]
I'll look into it

**Comment by dkazanc** [comment]
I guess this is obsolete now...
