### ISSUE TITLE
migrate repo to TomographicImaging

### ISSUE THREAD

**Issue by casperdcl** [TomographicImaging/CCPi-Regularisation-Toolkit#181]
[transfer repo](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/transfer) from @vais-ral to @TomographicImaging

Also would allow CI testing using @TomographicImaging's GPU runners.

/CC @dkazanc

**Comment by gfardell** [comment]
If @dkazanc is happy for it to move? It should make it easier to support.

**Comment by dkazanc** [comment]
@casperdcl @gfardell @paskino many thanks, I'm happy with the move.
