### ISSUE TITLE
Python/NumPy support matrix

### ISSUE THREAD

**Issue by paskino** [TomographicImaging/CCPi-Regularisation-Toolkit#194]
It would be good to support the same Python/NumPy as CIL

https://github.com/TomographicImaging/CIL/issues/1719

Python:
  - 3.10
  - 3.11
  - 3.12

NumPy:
  - 1.23
  - 1.24
  - 1.25
  - 1.26

**Comment by casperdcl** [comment]
related: https://github.com/TomographicImaging/CIL/issues/1719
