### ISSUE TITLE
Issue with 3D GPU regularisers in v. 24.0.0

### ISSUE THREAD

**Issue by dkazanc** [TomographicImaging/CCPi-Regularisation-Toolkit#204]
Thanks a lot for refactoring guys! While I was fiddling with the toolkit to make it work for ToMoBAR, I noticed that the output volumes in `demo_gpu_regularisers3D.py` are not good (see the image below). That is also consistent across all regularisers. 

I've tested 2D regularisers and they seem to be OK, so it is only 3D by the look of it. I know that input parameters have been slightly reshuffled for modules, so I checked that they in accordance to low-level functions. Doesn't seem to be the issue. 
In addition, the CuPy methods do produce correct results, so it must be something else. 
See that to reproduce the image below I've changed parameters slightly. We need to add 3D tests :) 

![Screenshot from 2024-05-03 15-36-45](https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/assets/6651977/bbbaf1be-3810-43dd-a05d-4ed95b56d021)

**Comment by paskino** [comment]
Looking at the reconstructed volume on the other directions I see:

![image](https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/assets/14138589/9451ce3b-eb6e-4ba7-b025-5b0d1ad026cc)

**Comment by paskino** [comment]
I think it is a general problem that you are seeing only in 3D because the X-Y dimensions are equal. This seems to be due to inversion of the dimensions passed to the underlying C functions.

**Comment by dkazanc** [comment]
Thanks @paskino, are you currently running CPU 3D regularisers or the GPU one?  I can confirm only that I saw it with GPU. I'll come back to it later today, I also did some corrections so that the CuPy part gets installed as well (as it wasn't before).

**Comment by paskino** [comment]
I fixed both CPU and GPU regularisers.

@dkazanc I suggest we merge #205 and open an issue about adding unit tests.
